services:
  - type: web
    name: health-monitor-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: JWT_EXPIRE
        value: 7d
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false

  - type: web
    name: health-monitor-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_BASE_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html